// 100 video game trivia questions. `answer` is the index of the correct option.
// Each question carries a fun fact shown after answering, plus a
// difficulty tag (easy/medium/hard) and a franchise tag for gameplay scaling.

export const QUESTIONS = [
  {
    q: "In Resident Evil, which shady company is behind the zombie-creating T-Virus?",
    options: ["Stark Industries", "Umbrella Corporation", "Wayne Enterprises", "Cyberdyne Systems"],
    answer: 1,
    fact: "Umbrella's logo is literally an umbrella, which is either great branding or the least subtle evil corporation ever.",
    difficulty: "easy",
    franchise: "Resident Evil",
  },
  {
    q: "What does the T-Virus do to people in Resident Evil?",
    options: ["Turns them into superheroes", "Lets them time travel", "Makes them great at karaoke", "Turns them into zombies"],
    answer: 3,
    fact: "The T-Virus is basically the reason every horror movie character should have just stayed home.",
    difficulty: "easy",
    franchise: "Resident Evil",
  },
  {
    q: "In Resident Evil 2, Leon S. Kennedy shows up for his first day as a what?",
    options: ["Police officer", "Pizza delivery driver", "Zookeeper", "Lifeguard"],
    answer: 0,
    fact: "Worst first day at work in history. Nobody warns you about that in the interview.",
    difficulty: "easy",
    franchise: "Resident Evil",
  },
  {
    q: "Kratos from God of War is known as the God of what?",
    options: ["Thunder", "Hugs", "War", "Farming"],
    answer: 2,
    fact: "He earned the title the hard way: by being extremely, extremely angry about everything.",
    difficulty: "easy",
    franchise: "God of War",
  },
  {
    q: "What is the name of Kratos's son in God of War (2018)?",
    options: ["Thor", "Atreus", "Loki", "Zeus Jr."],
    answer: 1,
    fact: "The whole game is basically one long, very violent father-son bonding trip.",
    difficulty: "easy",
    franchise: "God of War",
  },
  {
    q: "What are Kratos's signature chained weapons called?",
    options: ["Lightsabers", "Butter knives", "Nunchucks", "Blades of Chaos"],
    answer: 3,
    fact: "They are chained to his arms forever, which makes hugs complicated.",
    difficulty: "easy",
    franchise: "God of War",
  },
  {
    q: "In Ratchet & Clank, Clank is a what?",
    options: ["Robot", "Pirate", "Dragon", "Accountant"],
    answer: 0,
    fact: "He is a tiny robot who rides around in Ratchet's backpack like the galaxy's most useful luggage.",
    difficulty: "easy",
    franchise: "Ratchet & Clank",
  },
  {
    q: "What species is Ratchet from Ratchet & Clank?",
    options: ["Wookiee", "Smurf", "Lombax", "Minion"],
    answer: 2,
    fact: "Lombaxes look like cat-fox engineers, which is honestly elite character design.",
    difficulty: "easy",
    franchise: "Ratchet & Clank",
  },
  {
    q: "What trusty tool does Ratchet always carry in Ratchet & Clank?",
    options: ["Lasso", "OmniWrench", "Fishing rod", "Hair dryer"],
    answer: 1,
    fact: "The OmniWrench fixes things and bonks robots. A true multitool.",
    difficulty: "easy",
    franchise: "Ratchet & Clank",
  },
  {
    q: "What is Mario's day job?",
    options: ["Chef", "Accountant", "Plumber", "Astronaut"],
    answer: 2,
    fact: "A plumber who never fixes a single pipe. He just jumps on turtles for a living.",
    difficulty: "easy",
    franchise: "Super Mario",
  },
  {
    q: "What is the name of the green-clad hero of The Legend of Zelda?",
    options: ["Link", "Zelda", "Ganon", "Navi"],
    answer: 0,
    fact: "Zelda is the princess. Getting this wrong is the official rite of passage for non-gamers.",
    difficulty: "easy",
    franchise: "The Legend of Zelda",
  },
  {
    q: "What type of Pokemon is Pikachu?",
    options: ["Water", "Fire", "Grass", "Electric"],
    answer: 3,
    fact: "Pikachu is an Electric-type, which explains the cheeks that could power a small city.",
    difficulty: "easy",
    franchise: "Pokemon",
  },
  {
    q: "What color is Master Chief's iconic armor in Halo?",
    options: ["Pink", "Green", "Gold", "Neon purple"],
    answer: 1,
    fact: "Big green space armor. You could spot him from orbit, which is arguably a stealth problem.",
    difficulty: "easy",
    franchise: "Halo",
  },
  {
    q: "In Minecraft, what do you punch at the start to get wood?",
    options: ["Trees", "Clouds", "Other players' feelings", "The moon"],
    answer: 0,
    fact: "The tutorial for Minecraft is just: punch a tree. Gaming at its purest.",
    difficulty: "easy",
    franchise: "Minecraft",
  },
  {
    q: "Sonic the Hedgehog is what kind of animal?",
    options: ["Porcupine", "Sloth", "Hedgehog", "Armadillo"],
    answer: 2,
    fact: "It is right there in the name, but the speed makes him easy to misidentify.",
    difficulty: "easy",
    franchise: "Sonic the Hedgehog",
  },
  {
    q: "What are the big yellow rideable birds called in Final Fantasy?",
    options: ["Spaceship", "Chocobo", "Dragon", "Pizza"],
    answer: 1,
    fact: "Chocobos go kweh, which is the entire reason they are beloved.",
    difficulty: "easy",
    franchise: "Final Fantasy",
  },
  {
    q: "What is Solid Snake famous for in Metal Gear?",
    options: ["Cooking", "Dancing", "Speedrunning", "Stealth"],
    answer: 3,
    fact: "He once took on an entire army by hiding in a cardboard box. Stealth legend.",
    difficulty: "easy",
    franchise: "Metal Gear",
  },
  {
    q: "What does GTA stand for in Grand Theft Auto?",
    options: ["Get That Avocado", "Go Take Action", "Grand Theft Auto", "Good Times Ahead"],
    answer: 2,
    fact: "It refers to stealing cars, which tells you exactly what kind of game you are getting into.",
    difficulty: "easy",
    franchise: "Grand Theft Auto",
  },
  {
    q: "In The Elder Scrolls V: Skyrim, what legendary creatures return to cause chaos?",
    options: ["Dragons", "Unicorns", "Politicians", "Tax collectors"],
    answer: 0,
    fact: "The dragons are back, and the locals greet them with arrows and ancient shouting magic.",
    difficulty: "easy",
    franchise: "The Elder Scrolls",
  },
  {
    q: "What is the name of Ryu's famous fireball attack in Street Fighter?",
    options: ["Abracadabra", "Hocus Pocus", "Shazam", "Hadouken"],
    answer: 3,
    fact: "Players have been yelling Hadouken at their TVs since 1987.",
    difficulty: "easy",
    franchise: "Street Fighter",
  },
  {
    q: "In Mortal Kombat, when you hear Finish Him, what is about to happen?",
    options: ["A nap", "A group hug", "A tea break", "A fatality"],
    answer: 3,
    fact: "A fatality: an over-the-top finishing move that made parents in the 90s very nervous.",
    difficulty: "easy",
    franchise: "Mortal Kombat",
  },
  {
    q: "In Doom, what are you blasting on Mars?",
    options: ["Demons", "Homework", "Traffic", "Mosquitoes"],
    answer: 0,
    fact: "Demons invaded Mars, so one very ripped space marine handles it personally.",
    difficulty: "easy",
    franchise: "Doom",
  },
  {
    q: "In Portal, the cake is a what?",
    options: ["Delicious dessert", "Lie", "Birthday surprise", "In the fridge"],
    answer: 1,
    fact: "The cake is a lie: gaming's most famous broken promise, courtesy of a passive-aggressive AI.",
    difficulty: "easy",
    franchise: "Portal",
  },
  {
    q: "The Fallout games take place in a world ruined by what?",
    options: ["A zombie prom", "An alien talent show", "Nuclear war", "A really bad haircut"],
    answer: 2,
    fact: "The tagline says it best: war never changes, and the vending machines get weird.",
    difficulty: "easy",
    franchise: "Fallout",
  },
  {
    q: "Red Dead Redemption is set in which era?",
    options: ["Space", "The Wild West", "Underwater", "Medieval times"],
    answer: 1,
    fact: "Cowboys, horses, and dramatic standoffs. It is basically a playable western movie.",
    difficulty: "easy",
    franchise: "Red Dead Redemption",
  },
  {
    q: "What does Geralt of Rivia hunt for a living in The Witcher?",
    options: ["Coupons", "Parking spots", "Wi-Fi signals", "Monsters"],
    answer: 3,
    fact: "He is a monster hunter for hire, and yes, he charges extra for the dramatic entrance.",
    difficulty: "easy",
    franchise: "The Witcher",
  },
  {
    q: "What is the name of the demon-hunting hero of Devil May Cry?",
    options: ["Dante", "Mario", "Link", "Gordon"],
    answer: 0,
    fact: "Dante fights demons with style points. Literally: the game grades your combos.",
    difficulty: "easy",
    franchise: "Devil May Cry",
  },
  {
    q: "How does Crash Bandicoot usually attack enemies?",
    options: ["Crying", "Running away", "Spinning like a tornado", "Filing taxes"],
    answer: 2,
    fact: "The spin attack: part tornado, part marsupial, all orange.",
    difficulty: "easy",
    franchise: "Crash Bandicoot",
  },
  {
    q: "Spyro is what kind of creature?",
    options: ["Unicorn", "Dragon", "Frog", "Sentient burrito"],
    answer: 1,
    fact: "A small purple dragon with a big attitude and an even bigger fire-breathing talent.",
    difficulty: "easy",
    franchise: "Spyro",
  },
  {
    q: "The hero Samus Aran from Metroid is famously revealed to be what?",
    options: ["A robot", "A man", "An alien", "A woman"],
    answer: 3,
    fact: "One of gaming's first big twists: the armored bounty hunter was a woman all along.",
    difficulty: "easy",
    franchise: "Metroid",
  },
  {
    q: "What color is Kirby, the round Nintendo hero who inhales enemies?",
    options: ["Pink", "Blue", "Invisible", "Plaid"],
    answer: 0,
    fact: "Pink, round, and bottomless. Kirby could eat your house and ask for seconds.",
    difficulty: "easy",
    franchise: "Kirby",
  },
  {
    q: "What does Donkey Kong famously throw at Mario?",
    options: ["Bananas", "Pianos", "Barrels", "His back out"],
    answer: 2,
    fact: "Barrels. An ape with infinite barrels and zero mercy.",
    difficulty: "easy",
    franchise: "Donkey Kong",
  },
  {
    q: "Tom Nook, the character who sells you a house in Animal Crossing, is what animal?",
    options: ["Dog", "Raccoon", "Cat", "Frog"],
    answer: 1,
    fact: "He is a raccoon businessman who will absolutely get his bells back. Pay up.",
    difficulty: "easy",
    franchise: "Animal Crossing",
  },
  {
    q: "What does Pac-Man spend his time eating in the maze?",
    options: ["Ghosts only", "Sandwiches", "Homework", "Dots"],
    answer: 3,
    fact: "He munches dots, dodges ghosts, and has been doing it since 1980. An icon.",
    difficulty: "easy",
    franchise: "Pac-Man",
  },
  {
    q: "In Resident Evil 4, what does Ada Wong drop from a helicopter for Leon to use against Saddler?",
    options: ["A rocket launcher", "A minigun", "A green herb", "A riot shotgun"],
    answer: 0,
    fact: "Nothing says 'I believe in you' like a stranger tossing military-grade explosives out of a helicopter. Thanks, Ada.",
    difficulty: "medium",
    franchise: "Resident Evil",
  },
  {
    q: "In the Resident Evil 4 remake, what is the name of the lake monster boss Leon fights on the boat?",
    options: ["El Gigante", "Bitores Mendez", "Del Lago", "Verdugo"],
    answer: 2,
    fact: "Del Lago is basically a giant salamander with a grudge and terrible table manners. Harpoons only, no refunds.",
    difficulty: "medium",
    franchise: "Resident Evil",
  },
  {
    q: "In Resident Evil 4, what currency does the Merchant accept for weapons and upgrades?",
    options: ["Gil", "Rupees", "Bottlecaps", "Pesetas"],
    answer: 3,
    fact: "The Merchant takes pesetas and rhymes while doing it. 'Got some rare things on sale, stranger' is legally a personality at this point.",
    difficulty: "medium",
    franchise: "Resident Evil",
  },
  {
    q: "In God of War (2018), what is the name of Kratos's magical ice axe?",
    options: ["Mjölnir", "Stormbreaker", "The Blades of Chaos", "The Leviathan Axe"],
    answer: 3,
    fact: "The Leviathan Axe flies back to Kratos's hand like a very cold, very murderous boomerang. It was a gift from his late wife, which is sweet until you see what it does to draugr.",
    difficulty: "medium",
    franchise: "God of War",
  },
  {
    q: "In God of War (2018), in which realm do Kratos and Atreus finally scatter Faye's ashes?",
    options: ["Midgard", "Alfheim", "Jotunheim", "Muspelheim"],
    answer: 2,
    fact: "Jotunheim, the giants' realm, hidden at the top of the tallest peak. The whole game was basically one very long funeral procession with combat.",
    difficulty: "medium",
    franchise: "God of War",
  },
  {
    q: "In God of War Ragnarök, what is the name of the magical spear Kratos forges?",
    options: ["Gungnir", "The Draupnir Spear", "Gaé Bolg", "The Spear of Leonidas"],
    answer: 1,
    fact: "The Draupnir Spear multiplies itself infinitely, which is Kratos's way of saying he has run out of patience for throwing a finite number of things.",
    difficulty: "medium",
    franchise: "God of War",
  },
  {
    q: "What is the name of Ratchet's home planet in Ratchet & Clank?",
    options: ["Veldin", "Novalis", "Kerwan", "Quartu"],
    answer: 0,
    fact: "Veldin: home of Kyzil Plateau, Ratchet's garage, and apparently zero adult supervision for a teenage Lombax mechanic.",
    difficulty: "medium",
    franchise: "Ratchet & Clank",
  },
  {
    q: "In Ratchet & Clank, which weapon transforms enemies into harmless sheep?",
    options: ["The Sheepinator", "The Morph-o-Ray", "The Bouncer", "The RYNO"],
    answer: 1,
    fact: "The Morph-o-Ray turns your deadliest foes into fluffy sheep that just wander around going 'baa.' Honestly the most humane weapon in the galaxy.",
    difficulty: "medium",
    franchise: "Ratchet & Clank",
  },
  {
    q: "In Ratchet & Clank: Rift Apart, what is the name of the female Lombax from another dimension?",
    options: ["Angela", "Rivet", "Talwyn", "Sasha"],
    answer: 1,
    fact: "Rivet is a Lombax resistance fighter with a hammer bigger than she is and zero tolerance for emperors. Instant fan favorite.",
    difficulty: "medium",
    franchise: "Ratchet & Clank",
  },
  {
    q: "In Super Mario 64, how many Power Stars must you collect to unlock the final Bowser level?",
    options: ["50", "70", "80", "100"],
    answer: 2,
    fact: "80 stars opens the endless stairs to Bowser in the Sky, and yes, the stairs actually are endless if you try to sneak up with fewer.",
    difficulty: "medium",
    franchise: "Super Mario",
  },
  {
    q: "In The Legend of Zelda: Majora's Mask, which mask lets Link run significantly faster?",
    options: ["The Blast Mask", "The Stone Mask", "The Bunny Hood", "The Bremen Mask"],
    answer: 2,
    fact: "The Bunny Hood gives Link long ears and Olympic-sprinter legs. Fashion and function in one cursed accessory.",
    difficulty: "medium",
    franchise: "The Legend of Zelda",
  },
  {
    q: "In Pokémon Red and Blue, if you choose Charmander as your starter, which Pokémon does your rival pick?",
    options: ["Bulbasaur", "Pikachu", "Eevee", "Squirtle"],
    answer: 3,
    fact: "Your rival always picks the starter with the type advantage over yours, because the game wants you to suffer specifically.",
    difficulty: "medium",
    franchise: "Pokemon",
  },
  {
    q: "In the Halo series, what is the name of the Flood's ancient, tentacled central intelligence?",
    options: ["The Didact", "The Harbinger", "The Warden", "The Gravemind"],
    answer: 3,
    fact: "The Gravemind is a planet-sized pile of Flood flesh that speaks in creepy poetry. It once gave Cortana the worst road trip of her life.",
    difficulty: "medium",
    franchise: "Halo",
  },
  {
    q: "In Minecraft, which block cannot be destroyed by the Wither's explosions?",
    options: ["Obsidian", "Bedrock", "Ancient debris", "Crying obsidian"],
    answer: 1,
    fact: "Bedrock is the game's way of saying 'this far and no further.' Even a three-headed flying skeleton boss respects the bedrock.",
    difficulty: "medium",
    franchise: "Minecraft",
  },
  {
    q: "In Sonic the Hedgehog 2, what is the name of Tails' red biplane?",
    options: ["The Tornado", "The Hurricane", "The Cyclone", "The Whirlwind"],
    answer: 0,
    fact: "The Tornado is Tails' beloved plane, which he built himself at age eight. Child labor laws do not apply to foxes with two tails.",
    difficulty: "medium",
    franchise: "Sonic the Hedgehog",
  },
  {
    q: "In Final Fantasy VII, what is Cloud Strife's ultimate Limit Break?",
    options: ["Braver", "Cross-slash", "Climhazzard", "Omnislash"],
    answer: 3,
    fact: "Omnislash is fifteen sword hits in a blur, unlocked by winning it at the Gold Saucer battle arena. Peak 1997 flex.",
    difficulty: "medium",
    franchise: "Final Fantasy",
  },
  {
    q: "In Metal Gear Solid 3, what happens if you save during The End boss fight and don't play for over a week?",
    options: ["The End dies of old age", "The End ambushes you instantly", "Your save file corrupts", "Ocelot replaces him"],
    answer: 0,
    fact: "The End is an ancient sniper, so waiting him out literally works — he dies of old age. The most passive-aggressive boss kill in gaming history.",
    difficulty: "medium",
    franchise: "Metal Gear",
  },
  {
    q: "In Grand Theft Auto V, what is the name of Franklin's Rottweiler?",
    options: ["Chop", "Digger", "Rex", "Boomer"],
    answer: 0,
    fact: "Chop is Franklin's loyal dog, who you can even play fetch with via the phone app. Good boy, Los Santos division.",
    difficulty: "medium",
    franchise: "Grand Theft Auto",
  },
  {
    q: "In The Elder Scrolls V: Skyrim, which Dragon Shout do the Greybeards teach you first?",
    options: ["Fire Breath", "Become Ethereal", "Unrelenting Force", "Storm Call"],
    answer: 2,
    fact: "Unrelenting Force, or Fus Ro Dah, is the shout every player spams off cliffs and at shopkeepers. The Greybeards regret everything.",
    difficulty: "medium",
    franchise: "The Elder Scrolls",
  },
  {
    q: "In Dark Souls, what item must you offer at a bonfire to kindle it and get extra Estus Flasks?",
    options: ["Humanity", "Titanite Shards", "Souls", "Embers"],
    answer: 0,
    fact: "Offering Humanity kindles a bonfire from 5 flasks up to 10 or more. Nothing says cozy campfire like feeding it your own humanity.",
    difficulty: "medium",
    franchise: "Dark Souls",
  },
  {
    q: "In Elden Ring, which item allows you to summon Spirit Ashes to aid you in battle?",
    options: ["The Flask of Wondrous Physick", "The Spirit Calling Bell", "The Mimic's Veil", "The Lantern"],
    answer: 1,
    fact: "The Spirit Calling Bell is gifted by Renna at the Church of Elleh. Ring it and ghostly jellyfish have your back. No judgment.",
    difficulty: "medium",
    franchise: "Elden Ring",
  },
  {
    q: "In Street Fighter II, which fighter is a Muay Thai kickboxer from Thailand?",
    options: ["Balrog", "Vega", "Blanka", "Sagat"],
    answer: 3,
    fact: "Sagat is the scarred Muay Thai emperor with the infamous Tiger Uppercut. That chest scar? A gift from Ryu's Shoryuken.",
    difficulty: "medium",
    franchise: "Street Fighter",
  },
  {
    q: "In Mortal Kombat, which character is the four-armed Shokan prince?",
    options: ["Kintaro", "Sheeva", "Goro", "Motaro"],
    answer: 2,
    fact: "Goro, the four-armed Shokan prince, was the original arcade quarter-muncher. He has been ruining friendships since 1992.",
    difficulty: "medium",
    franchise: "Mortal Kombat",
  },
  {
    q: "In DOOM lore, what does BFG officially stand for?",
    options: ["Big Freaking Gun", "Blast Field Generator", "Big Fucking Gun", "Bio Force Gun"],
    answer: 3,
    fact: "The manual says Bio Force Gun, but the movie went with Big Fucking Gun, and honestly the fandom voted with its heart.",
    difficulty: "medium",
    franchise: "Doom",
  },
  {
    q: "In the original Portal, how many test chambers do you complete before the game goes off the rails?",
    options: ["12", "16", "19", "24"],
    answer: 2,
    fact: "There are 19 test chambers before things get spicy and GLaDOS tries to turn you into confetti. The cake was a lie, but the count was real.",
    difficulty: "medium",
    franchise: "Portal",
  },
  {
    q: "In Mass Effect 2, what is the name of the Normandy's upgraded replacement ship?",
    options: ["The Normandy SR-1", "The Tempest", "The Destiny Ascension", "The Normandy SR-2"],
    answer: 3,
    fact: "The Normandy SR-2 is Cerberus-built and twice as sleek. Shepard dies for two minutes and wakes up to a brand-new spaceship. Worth it?",
    difficulty: "medium",
    franchise: "Mass Effect",
  },
  {
    q: "In Fallout 3, what is the number of the Vault you grow up in?",
    options: ["Vault 13", "Vault 101", "Vault 111", "Vault 76"],
    answer: 1,
    fact: "Vault 101's motto is 'we are born in the vault, we die in the vault' — until your dad ruins everything by leaving. Classic dad move.",
    difficulty: "medium",
    franchise: "Fallout",
  },
  {
    q: "In Red Dead Redemption 2, what illness does Arthur Morgan contract partway through the story?",
    options: ["Scarlet fever", "Consumption", "Tuberculosis", "Cholera"],
    answer: 2,
    fact: "Arthur contracts tuberculosis after a debt-collection beating goes wrong. The toughest cowboy in the West, taken down by a cough.",
    difficulty: "medium",
    franchise: "Red Dead Redemption",
  },
  {
    q: "In The Witcher 3, what is the name Geralt gives to every one of his horses?",
    options: ["Roach", "Kelpie", "Scorpion", "Pegasus"],
    answer: 0,
    fact: "Every horse Geralt owns is named Roach. When one dies, the next one is also Roach. It's not denial, it's tradition.",
    difficulty: "medium",
    franchise: "The Witcher",
  },
  {
    q: "In Devil May Cry, what are the names of Dante's signature twin handguns?",
    options: ["Ebony & Ivory", "Luce & Ombra", "Alastor & Ifrit", "Nevan & Agni"],
    answer: 0,
    fact: "Ebony and Ivory are Dante's custom .45s, because nothing says style like naming your guns like piano keys.",
    difficulty: "medium",
    franchise: "Devil May Cry",
  },
  {
    q: "In the Crash Bandicoot games, what do you earn for collecting 100 Wumpa Fruit in a level?",
    options: ["A gem", "An extra life", "A key", "A crystal"],
    answer: 1,
    fact: "100 Wumpa Fruit equals one extra life, and you will need every single one. Those pit jumps are not forgiving.",
    difficulty: "medium",
    franchise: "Crash Bandicoot",
  },
  {
    q: "In Super Metroid, which beam upgrade lets Samus's shots pass through walls?",
    options: ["Ice Beam", "Spazer Beam", "Plasma Beam", "Wave Beam"],
    answer: 3,
    fact: "The Wave Beam's shots phase through solid rock, which is extremely convenient on a planet made almost entirely of walls.",
    difficulty: "medium",
    franchise: "Metroid",
  },
  {
    q: "In Hollow Knight, what currency do you drop in a Shade when you die?",
    options: ["Gems", "Geo", "Essence", "Soul"],
    answer: 1,
    fact: "You drop all your Geo and must fight your own angry ghost to get it back. Nothing motivates like getting mugged by yourself.",
    difficulty: "medium",
    franchise: "Hollow Knight",
  },
  {
    q: "The original Resident Evil (1996) began development as a remake of which 1989 Capcom horror game?",
    options: ["Sweet Home", "Clock Tower", "Alone in the Dark", "Splatterhouse"],
    answer: 0,
    fact: "Shinji Mikami's team started by remaking the Famicom horror RPG Sweet Home before it mutated into Resident Evil.",
    difficulty: "hard",
    franchise: "Resident Evil",
  },
  {
    q: "In the scrapped Resident Evil 1.5 build, who was Leon's partner before Claire Redfield replaced her?",
    options: ["Jill Valentine", "Elza Walker", "Ada Wong", "Rebecca Chambers"],
    answer: 1,
    fact: "Elza Walker, a motorcycle-riding college student, was Leon's original partner before Capcom trashed 1.5 and rewrote the story.",
    difficulty: "hard",
    franchise: "Resident Evil",
  },
  {
    q: "According to Resident Evil lore, who was the twisted architect that designed the Spencer Mansion?",
    options: ["Oswell E. Spencer", "James Marcus", "William Birkin", "George Trevor"],
    answer: 3,
    fact: "George Trevor built the mansion's death-trap halls, then Umbrella locked him inside his own creation. Rude.",
    difficulty: "hard",
    franchise: "Resident Evil",
  },
  {
    q: "Before Christopher Judge took over in 2018, who voiced Kratos in every earlier God of War game?",
    options: ["Christopher Judge", "T.C. Carson", "Michael Clarke Duncan", "Kevin Sorbo"],
    answer: 1,
    fact: "T.C. Carson growled as the Ghost of Sparta from 2005 to 2013 before Judge picked up the Leviathan Axe.",
    difficulty: "hard",
    franchise: "God of War",
  },
  {
    q: "What is the name of Kratos's young daughter, seen in flashbacks across the Greek-era games?",
    options: ["Calliope", "Pandora", "Lysandra", "Athena"],
    answer: 0,
    fact: "Little Calliope and her flute are the reason Kratos can never quite outrun his past.",
    difficulty: "hard",
    franchise: "God of War",
  },
  {
    q: "In Ghost of Sparta, Kratos searches for his long-lost brother. What is his name?",
    options: ["Baldur", "Deimos", "Magni", "Tyr"],
    answer: 1,
    fact: "Deimos was kidnapped by the gods as a kid, which is the whole reason Kratos has beef with Olympus.",
    difficulty: "hard",
    franchise: "God of War",
  },
  {
    q: "What is the name of Dr. Nefarious's long-suffering robotic butler?",
    options: ["Lawrence", "Clank", "Zed", "Copernicus"],
    answer: 0,
    fact: "Lawrence serves the galaxy's most dramatic evil genius and somehow keeps a straight face doing it.",
    difficulty: "hard",
    franchise: "Ratchet & Clank",
  },
  {
    q: "What is Captain Qwark's full, glorious real name?",
    options: ["Chad Qwarkington", "Quentin Lance Qwark", "Copernicus Leslie Qwark", "Bartholomew Qwark"],
    answer: 2,
    fact: "Copernicus Leslie Qwark. Try saying that with a straight face in a Qwark voice.",
    difficulty: "hard",
    franchise: "Ratchet & Clank",
  },
  {
    q: "Which Ratchet & Clank game introduced the evil Dr. Nefarious?",
    options: ["Ratchet & Clank (2002)", "Going Commando", "Tools of Destruction", "Up Your Arsenal"],
    answer: 3,
    fact: "Nefarious crashed the party in 2004's Up Your Arsenal and never left.",
    difficulty: "hard",
    franchise: "Ratchet & Clank",
  },
  {
    q: "The American Super Mario Bros. 2 was actually a reskinned version of which Japanese-only game?",
    options: ["Yume Kojo: Doki Doki Panic", "Wrecking Crew", "Devil World", "Clu Clu Land"],
    answer: 0,
    fact: "Nintendo thought the real SMB2 was too hard for the West, so Mario got a costume change over Fuji TV's Doki Doki Panic.",
    difficulty: "hard",
    franchise: "Super Mario",
  },
  {
    q: "Princess Zelda was named after the wife of which famous American novelist?",
    options: ["Ernest Hemingway", "F. Scott Fitzgerald", "Mark Twain", "John Steinbeck"],
    answer: 1,
    fact: "Miyamoto loved the name Zelda Fitzgerald so much he gave it to Hyrule's princess. Literary cred unlocked.",
    difficulty: "hard",
    franchise: "The Legend of Zelda",
  },
  {
    q: "Which of these Pokemon has a name that reads the same forwards and backwards?",
    options: ["Pikachu", "Charizard", "Eevee", "Mewtwo"],
    answer: 2,
    fact: "Eevee is a perfect palindrome, which is fitting for the Pokemon with the most identity crises.",
    difficulty: "hard",
    franchise: "Pokemon",
  },
  {
    q: "While in development at Bungie, Halo was known internally by what codename?",
    options: ["Marathon", "Phoenix", "Pillar", "Blam!"],
    answer: 3,
    fact: "Bungie called the project 'Blam!' and the name later lived on in the engine powering the series.",
    difficulty: "hard",
    franchise: "Halo",
  },
  {
    q: "When Markus 'Notch' Persson first released Minecraft in 2009, what was it called?",
    options: ["Block World", "Mine Builder", "Craft Game", "Cave Game"],
    answer: 3,
    fact: "Before it became Minecraft, Notch's little project was literally just called Cave Game. Humble beginnings.",
    difficulty: "hard",
    franchise: "Minecraft",
  },
  {
    q: "During early development, Sonic the Hedgehog was known by what codename?",
    options: ["Fast Blue", "Mr. Needlemouse", "Speedy Hog", "Turbo Spikes"],
    answer: 1,
    fact: "'Needlemouse' is a literal translation of the Japanese word for hedgehog. Sega's little inside joke.",
    difficulty: "hard",
    franchise: "Sonic the Hedgehog",
  },
  {
    q: "Why did Hironobu Sakaguchi call it 'Final' Fantasy?",
    options: ["It was the last NES game Square planned", "It was the final entry in a trilogy", "He believed it would be his last game", "The word tested well in focus groups"],
    answer: 2,
    fact: "Sakaguchi thought Square was going under and this would be his last shot. Spoiler: it was not.",
    difficulty: "hard",
    franchise: "Final Fantasy",
  },
  {
    q: "Raiden's codename in Metal Gear Solid 2 was inspired by what?",
    options: ["A thunderstorm", "A Shinto god", "A type of sword", "A Japanese WWII fighter plane"],
    answer: 3,
    fact: "The Mitsubishi J2M Raiden was a real WWII interceptor. Kojima just thought the name sounded cool.",
    difficulty: "hard",
    franchise: "Metal Gear",
  },
  {
    q: "The original Grand Theft Auto (1997) was developed under what working title?",
    options: ["Race'n'Chase", "Crime Wave", "Getaway", "Street Heat"],
    answer: 0,
    fact: "Before it was GTA, DMA Design called it Race'n'Chase, which honestly still slaps.",
    difficulty: "hard",
    franchise: "Grand Theft Auto",
  },
  {
    q: "The Elder Scrolls: Arena was originally designed as what kind of game?",
    options: ["A trading sim", "A gladiator combat game", "A naval strategy game", "A horse racing game"],
    answer: 1,
    fact: "Arena started as a game about gladiatorial arena combat. The RPG exploration got bolted on later and took over.",
    difficulty: "hard",
    franchise: "The Elder Scrolls",
  },
  {
    q: "In what year did Hidetaka Miyazaki join FromSoftware?",
    options: ["2001", "2007", "2004", "2010"],
    answer: 2,
    fact: "Miyazaki joined FromSoftware in 2004 as a planner on Armored Core, five years before Demon's Souls made him a legend.",
    difficulty: "hard",
    franchise: "Dark Souls",
  },
  {
    q: "In Street Fighter II, Ken originally started out as what?",
    options: ["A boss character", "A hidden unlockable", "A female fighter", "A palette swap of Ryu"],
    answer: 3,
    fact: "Ken was literally Ryu painted differently. The ultimate 'we have Ryu at home' situation.",
    difficulty: "hard",
    franchise: "Street Fighter",
  },
  {
    q: "The voice behind Mortal Kombat's iconic 'Toasty!' pop-up belongs to whom?",
    options: ["Dan Forden", "Ed Boon", "John Tobias", "Richard Divizio"],
    answer: 0,
    fact: "Sound designer Dan Forden recorded 'Toasty!' and his face pops up in the corner. He's been toasting noobs since 1993.",
    difficulty: "hard",
    franchise: "Mortal Kombat",
  },
  {
    q: "Early in development, Doom was conceived as a licensed game based on which film franchise?",
    options: ["The Terminator", "Aliens", "Predator", "RoboCop"],
    answer: 1,
    fact: "id Software couldn't get the Aliens license, so they made their own space-marine-versus-demons nightmare instead. Worked out okay.",
    difficulty: "hard",
    franchise: "Doom",
  },
  {
    q: "Portal was built from a student game project called what?",
    options: ["Tag: The Power of Paint", "Chromatron", "Narbacular Drop", "Perspective"],
    answer: 2,
    fact: "Valve hired the DigiPen students behind Narbacular Drop and turned their portal-puzzle homework into a masterpiece.",
    difficulty: "hard",
    franchise: "Portal",
  },
  {
    q: "Fallout is considered the spiritual successor to which 1988 RPG?",
    options: ["Ultima IV", "The Bard's Tale", "Might and Magic", "Wasteland"],
    answer: 3,
    fact: "Interplay couldn't get the Wasteland license from EA, so they made Fallout instead. The post-apocalypse's greatest legal loophole.",
    difficulty: "hard",
    franchise: "Fallout",
  },
  {
    q: "Who voiced and motion-captured John Marston in Red Dead Redemption?",
    options: ["Rob Wiethoff", "Roger Clark", "Nolan North", "Troy Baker"],
    answer: 0,
    fact: "Rob Wiethoff's gruff drawl defined John Marston, and he had almost no acting experience before landing the role.",
    difficulty: "hard",
    franchise: "Red Dead Redemption",
  },
  {
    q: "What did Andrzej Sapkowski famously accept for The Witcher video game rights instead of royalties?",
    options: ["A cameo in the game", "A one-time lump-sum payment", "A share of CD Projekt stock", "Creative control over the story"],
    answer: 1,
    fact: "Sapkowski took the cash up front, confident games would flop. The games then made hundreds of millions. Ouch.",
    difficulty: "hard",
    franchise: "The Witcher",
  },
  {
    q: "Devil May Cry began development as an early version of which other Capcom game?",
    options: ["Onimusha", "Dino Crisis 2", "Resident Evil 4", "Chaos Legion"],
    answer: 2,
    fact: "Hideki Kamiya's 'stylish' take on RE4 was too action-heavy for horror, so Capcom spun it off into Devil May Cry.",
    difficulty: "hard",
    franchise: "Devil May Cry",
  },
  {
    q: "What does the Japanese word 'Tekken' translate to in English?",
    options: ["Steel Thunder", "Fighting Spirit", "Warrior's Path", "Iron Fist"],
    answer: 3,
    fact: "'Iron Fist', which is exactly what the King of Iron Fist Tournament promises on the tin.",
    difficulty: "hard",
    franchise: "Tekken",
  },
  {
    q: "During early development, Crash Bandicoot was known by what name?",
    options: ["Willie the Wombat", "Ozzy the Orange", "Willy the Wildcat", "Crash Coyote"],
    answer: 0,
    fact: "Naughty Dog's hero was almost 'Willie the Wombat'. 'Crash Bandicoot' was a serious upgrade.",
    difficulty: "hard",
    franchise: "Crash Bandicoot",
  },
  {
    q: "Who composed the music for the original Spyro the Dragon (1998)?",
    options: ["Mark Mothersbaugh", "Danny Elfman", "Stewart Copeland", "Tommy Tallarico"],
    answer: 2,
    fact: "The Police's drummer Stewart Copeland gave Spyro its jazzy, bouncy soundtrack. Dragons have never grooved harder.",
    difficulty: "hard",
    franchise: "Spyro",
  },
  {
    q: "The name 'Metroid' is a combination of which two words?",
    options: ["Meteor and droid", "Metropolis and void", "Metro and android", "Metal and asteroid"],
    answer: 2,
    fact: "'Metro' plus 'android', because Samus rides the subway of killer robots, apparently.",
    difficulty: "hard",
    franchise: "Metroid",
  },
  {
    q: "Kirby was named after whom?",
    options: ["A Nintendo executive", "A Japanese candy brand", "Miyamoto's childhood dog", "Nintendo's lawyer John Kirby"],
    answer: 3,
    fact: "John Kirby was the lawyer who saved Nintendo from Universal's Donkey Kong lawsuit, so they named a pink puffball after him.",
    difficulty: "hard",
    franchise: "Kirby",
  },
];

// Verdict tiers based on final score out of 100.
export function getVerdict(score) {
  if (score >= 90)
    return {
      title: "CERTIFIED DAY-ONE FAN",
      line: "You don't just play games. You ARE games.",
    };
  if (score >= 75)
    return {
      title: "REAL FAN",
      line: "Respect. Your gamer card is fully intact.",
    };
  if (score >= 60)
    return {
      title: "SOLID CASUAL",
      line: "You play games. But do you PLAY games?",
    };
  if (score >= 40)
    return {
      title: "SUS",
      line: "Some of those answers were... brave.",
    };
  if (score >= 20)
    return {
      title: "CASUAL LARPER",
      line: "You watched one speedrun and ran with it.",
    };
  return {
    title: "EXPOSED LARPER",
    line: "The council has reviewed your answers. It's not looking good.",
  };
}

// Fisher-Yates shuffle so the question order is fresh every game.
export function shuffled(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
